---
layout: single
title:  "백준 10951 파이썬 문제풀이"
excerpt: "try구문, 백준 10951번 풀이 "

categories:
- Algorithm

tags:
- [Python, Algorithm]

date: 2022-04-24
published: true
---

### 문제

두 정수 a와 b를 입력받은 다음, a+b를 출력하는 프로그램을 작성하시오.

### 입력값

입력은 여려개의 테스트 케이스로 이루어져 있다.

각 테스트 케이스는 한 줄로 이루어져 있으며, 각 줄에 a와 b가 주어진다.(0<a, b<10)

### 출력값

a+b

위 문제에 대한 내가 짠 첫번째 코드는 다음과 같다.
```python
while 1:      #반복문 1=true
    a,b = map(int, input().split())   #입력값 a,b 정수화
    print(a+b)          # print
```

위 코드에는 다음과 같은 오류가 있다.

- 반복문의 종결조건이 명확하지 않다.
- a와 b의 조건이 없다.

2번의 문제는 간단히 조건만 추가해주면 해결되지만 종결조건의 경우 방법이 생각나지 않았다.

그래서 구글링을 해본 결과  try, except, else, finally 구문을 통해 해결가능하다.

try 구문은 오류가 발생할 것으로 예상되는 코드에 적용가능한데

예를 들면 위 문제처럼 종결조건이 명시되지않은 코드에 적용가능하다.

적용 예(10951정답)
```python

while 1:
    try:
        a,b = map(int, input().split())  #a,b에 int형 자료가 들어간다면 a+b를 출력
        print(a+b)
    except:   #try에 대한 에러가 발생한경우
        break   #while문을 멈춘다.
```
위와 같이 try, except 구문을 통해 문제를 해결할 수 있다.

### 추가적인 정보

## try, except, else의 예시

```python
try:
    ...
except 발생오류1:
    ...
else:
    ... 
```
발생오류가 다양한 경우 위와 같이 발생오류1의 경우 except를 통해 조치하고 그외의 경우는 else 구문을 통해 조치하도록 할 수 있다.

***else의 경우 except없이는 사용할 수 없음***

## try, finally 구문 예시

```python
try:  
    ...
finally:
    ...

```
finally의 경우 try문 수행 도중 예외 발생 여부에 상관없이 항상 수행된다.

